package whalethedvaa.whalethedvaa

import android.support.v7.app.AppCompatActivity
import android.os.Bundle
import android.support.v7.app.AlertDialog
import android.widget.TextView
import kotlinx.android.synthetic.main.activity_insecure_logging.*

class InsecureLogging : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {

        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_insecure_logging)
        val level = intent.getIntExtra("Level",0) //Read in the difficulty selection

        fun readFromAssets(){

            var fileName = "default"

            when(level) {                                           //Uses different txt files for the three difficulties
                1 -> fileName = "InsecureLogging_1_Easy.txt"
                2 -> fileName = "InsecureLogging_3_Killer.txt"
                3 -> fileName = "InsecureLogging_2_Medium.txt"
            }

            //This code reads in the text using a buffered reader
            val content = application.assets.open(fileName).bufferedReader().use{
                it.readText()
            }
            //Then this code sets the text to the textview
            val textView: TextView = findViewById(R.id.txtField) as TextView
            textView.text = content

            //Some mild error catching
            if (fileName == "default"){
                textView.text = "//ERROR// - - //DIFF_SELECT_LOGGING//"
            }

        }
        informationDialog()     //OnCreate, pop up the information dialog
        readFromAssets()        //OnCreate, read the assets file

        //Setting Buttons to Listeners
        InformationBtn.setOnClickListener{
            informationDialog()
        }

        HintBtn.setOnClickListener{
            hintSelectionDialog()
        }

        BackBtn.setOnClickListener{
            onBackPressed()
        }
    }

    //Function to set the Info section of the code
    private fun informationDialog(){
        val builder = AlertDialog.Builder(this, R.style.whaleDialog)
        val level = intent.getIntExtra("Level",0)

        // Set the dialog title
        builder.setTitle("Insecure Logging Information")

        //Code to change the info for the different difficulty levels
        if (level == 1){
            builder.setMessage("You've been given access to a log file from a user's mobile phone. This information will allow you to investigate how the user interacted with their phone and apps.")
        }
        if (level == 2){
            builder.setMessage("In this example, you've still been given a log file. However more measures have been put in place in the apps the user has interacted with to avoid data leakage.")
        }
        if (level == 3){
            builder.setMessage("Again, you've been given access to a log file. This time the user interacts with some different applications which provides more information to what they were up to.")
        }

        //Creating the dialog
        val dialog: AlertDialog = builder.create()
        dialog.show()
    }

    //Create dialog to show the hints
    private fun hintSelectionDialog(){
        val builder = AlertDialog.Builder(this, R.style.whaleDialog)
        // Set the dialog title
        builder.setTitle("Hints")

        //Using chaining to set the values of the hints
        val hints = arrayOf("Hint 1", "Hint 2", "Hint 3")
        builder.setItems(hints){ _, which ->
            hintDialog(hints[which])
        }

        //Build the Dialog
        val dialog: AlertDialog = builder.create()
        dialog.show()
    }


    //Function to create the hint dialog
    private fun hintDialog(chosenHint: String)
    {
        val level = intent.getIntExtra("Level",0)
        val builder = AlertDialog.Builder(this, R.style.whaleDialog)
        // Set the dialog title
        builder.setTitle(chosenHint)

        //The code below sets the Hints to different things depending on the difficulty selection
        if(level == 1) {
            when (chosenHint) {
                "Hint 1" -> builder.setMessage("You've been given access to the log files generated by a user, can you find anything interesting?")
                "Hint 2" -> builder.setMessage("Look at the logs as a timeline of events, what is the user doing?")
                "Hint 3" -> builder.setMessage("You're looking for an event where the program outputs a Username and a Password, this is the flag!")
            }
        }
        if(level == 2) {
            when (chosenHint) {
                "Hint 1" -> builder.setMessage("Look at what the program is outputting to the log file, something about a file path?")
                "Hint 2" -> builder.setMessage("This exercise will require you to think outside the box, or ... outside the app?")
                "Hint 3" -> builder.setMessage("If you use the filesystem browser app on the phone, you can find the file by navigating to the filepath!")
            }
        }
        if(level == 3) {
            when (chosenHint) {
                "Hint 1" -> builder.setMessage("Something unusual happens in this log file, can you identify it?")
                "Hint 2" -> builder.setMessage("One of the apps crashes during running, this dumps a file called traces.txt")
                "Hint 3" -> builder.setMessage("By using the filesystem browser, as in the previous exercise, you can navigate to this file and find the flag!")
            }
        }

        //Create the dialog
        val dialog: AlertDialog = builder.create()
        dialog.show()
    }
}
